#!/usr/bin/env bash
#
# build.sh — assemble lib/*.sh modules + the ss-easy entrypoint into a single
# runnable bundle at dist/ss-easy for `curl | bash` distribution.
#
# The bundle has exactly one shebang and one `set -euo pipefail` (from the
# generated header); module/entrypoint shebangs are stripped, and the
# entrypoint's dev-mode source of lib/common.sh is removed since the modules are
# already inlined. Module concatenation order is deterministic (sorted).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${ROOT}/lib"
ENTRY="${ROOT}/ss-easy"
DIST_DIR="${ROOT}/dist"
OUT="${DIST_DIR}/ss-easy"
CHECKSUMS_FILE="${ROOT}/checksums/ss-rust.sha256"

[ -f "$ENTRY" ] || { echo "build: entrypoint not found: $ENTRY" >&2; exit 1; }

# --- keep embedded ss-rust checksums in sync --------------------------------
#
# checksums/ss-rust.sha256 is the single source of truth (human/CI-readable).
# The installed single-file bundle has no sibling files, so binary.sh verifies
# the download against EMBEDDED constants instead. Regenerate that embedded block
# from the checksums file on every build so the two can never drift. Each file
# line is `<sha256>  shadowsocks-<ver>.<triple>.tar.xz`; we emit one constant
# `_SS_RUST_SHA256_<triple-with-_>="<hash>"` per line, between the managed
# sentinels in lib/binary.sh.
_ss_sync_embedded_checksums() {
  local binary="${LIB_DIR}/binary.sh"
  [ -f "$CHECKSUMS_FILE" ] || { echo "build: checksum table not found: $CHECKSUMS_FILE" >&2; exit 1; }
  [ -f "$binary" ] || { echo "build: binary module not found: $binary" >&2; exit 1; }

  local block tmp
  block="$(
    while read -r sum asset; do
      [ -n "$sum" ] || continue
      # asset: shadowsocks-<version>.<triple>.tar.xz. The version itself contains
      # dots, so a prefix glob is ambiguous; match the trailing Rust triple
      # (<cpu>-<vendor>-linux-<libc>) directly instead.
      local base="${asset%.tar.xz}" triple=""
      if [[ "$base" =~ ([A-Za-z0-9_]+-[A-Za-z0-9_]+-linux-[A-Za-z0-9_]+)$ ]]; then
        triple="${BASH_REMATCH[1]}"
      else
        echo "build: cannot parse triple from asset: $asset" >&2; exit 1
      fi
      printf '_SS_RUST_SHA256_%s="%s"\n' "${triple//[-.]/_}" "$sum"
    done < "$CHECKSUMS_FILE"
  )"

  [ -n "$block" ] || { echo "build: no checksum lines parsed from $CHECKSUMS_FILE" >&2; exit 1; }

  # Replace everything between the BEGIN/END sentinels (exclusive) with the
  # freshly generated constants. awk keeps the sentinel lines themselves.
  tmp="$(mktemp "${LIB_DIR}/.binary.XXXXXX")"
  awk -v block="$block" '
    /EMBEDDED-CHECKSUMS:BEGIN/ { print; print block; skip = 1; next }
    /EMBEDDED-CHECKSUMS:END/   { skip = 0; print; next }
    skip == 1                  { next }
    { print }
  ' "$binary" > "$tmp"
  chmod --reference="$binary" "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$binary"
}

_ss_sync_embedded_checksums

mkdir -p "$DIST_DIR"

# Build into a temp file first so a failed build never leaves a partial bundle.
tmp="$(mktemp "${DIST_DIR}/.build.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

# inline_source <file> — emit a file's body for the bundle. Drops the shebang
# and any standalone `set -euo pipefail` (the generated header owns both), and
# deletes every dev-only sibling-source region delimited by the explicit
# `# build:strip-start` / `# build:strip-end` sentinels. Those regions source a
# sibling lib/*.sh so the module is usable standalone in dev/tests; in the
# bundle the modules are already inlined, so the sibling sourcing must not run.
# Sentinel markers (not regex guesses) make stripping uniform and robust across
# every module variant and the entrypoint.
inline_source() {
  awk '
    /^[[:space:]]*# build:strip-start[[:space:]]*$/ { strip = 1; next }
    /^[[:space:]]*# build:strip-end[[:space:]]*$/   { strip = 0; next }
    strip == 1                   { next }
    /^#!/                        { next }
    /^set -euo pipefail$/        { next }
    { print }
  ' "$1"
}

{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by build.sh — do not edit. Edit lib/*.sh and ss-easy instead.\n'
  printf 'set -euo pipefail\n\n'

  # Inline every module. common.sh is the shared base every other module depends
  # on (constants and primitives referenced at module load time, e.g.
  # SS_RUST_VERSION, SS_SERVICE_NAME), so it MUST come first; the remaining
  # modules are independent of each other at load time and follow in a stable,
  # sorted order. In dev each module sources common.sh itself (those strip
  # regions are deleted above); the bundle relies on this ordering instead.
  if compgen -G "${LIB_DIR}/*.sh" > /dev/null; then
    common="${LIB_DIR}/common.sh"
    if [ -f "$common" ]; then
      printf '# --- module: %s ---\n' "$(basename "$common")"
      inline_source "$common"
      printf '\n'
    fi
    for module in $(printf '%s\n' "${LIB_DIR}"/*.sh | LC_ALL=C sort); do
      [ "$module" = "$common" ] && continue
      printf '# --- module: %s ---\n' "$(basename "$module")"
      inline_source "$module"
      printf '\n'
    done
  fi

  # Append the entrypoint body the same way: its dev-mode module-loading block is
  # delimited by the same strip sentinels, so it is removed here too.
  printf '# --- entrypoint: ss-easy ---\n'
  inline_source "$ENTRY"
} > "$tmp"

chmod 755 "$tmp"
mv -f "$tmp" "$OUT"
trap - EXIT

# Fail loudly if the produced bundle is not syntactically valid.
bash -n "$OUT" || { echo "build: generated bundle failed bash -n" >&2; exit 1; }

echo "build: wrote ${OUT}"
