#!/usr/bin/env bash
#
# build.sh — assemble lib/*.sh modules + the ss-easy entrypoint into a single
# runnable bundle at dist/ss-easy for `curl | bash` distribution.
#
# The bundle has exactly one shebang and one `set -euo pipefail` (from the
# generated header); module/entrypoint shebangs are stripped, and the
# entrypoint's dev-mode source of lib/common.sh is removed since the modules are
# already inlined. Module concatenation order is deterministic (sorted).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${ROOT}/lib"
ENTRY="${ROOT}/ss-easy"
DIST_DIR="${ROOT}/dist"
OUT="${DIST_DIR}/ss-easy"

[ -f "$ENTRY" ] || { echo "build: entrypoint not found: $ENTRY" >&2; exit 1; }

mkdir -p "$DIST_DIR"

# Build into a temp file first so a failed build never leaves a partial bundle.
tmp="$(mktemp "${DIST_DIR}/.build.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by build.sh — do not edit. Edit lib/*.sh and ss-easy instead.\n'
  printf 'set -euo pipefail\n\n'

  # Inline every module in a stable, sorted order. Strip each module's shebang
  # (if any) and any standalone `set -euo pipefail` to keep the bundle single.
  if compgen -G "${LIB_DIR}/*.sh" > /dev/null; then
    for module in $(printf '%s\n' "${LIB_DIR}"/*.sh | LC_ALL=C sort); do
      printf '# --- module: %s ---\n' "$(basename "$module")"
      grep -v -e '^#!' -e '^set -euo pipefail$' "$module"
      printf '\n'
    done
  fi

  # Append the entrypoint body without its shebang, its global `set` line, or
  # its dev-mode module-loading block (modules are already inlined above).
  printf '# --- entrypoint: ss-easy ---\n'
  awk '
    /^#!/                        { next }
    /^set -euo pipefail$/        { next }
    /^if \[ -z "\$\{_SS_EASY_COMMON_LOADED:-\}" \]; then$/ { skip = 1; next }
    skip == 1 && /^fi$/          { skip = 0; next }
    skip == 1                    { next }
    { print }
  ' "$ENTRY"
} > "$tmp"

chmod 755 "$tmp"
mv -f "$tmp" "$OUT"
trap - EXIT

# Fail loudly if the produced bundle is not syntactically valid.
bash -n "$OUT" || { echo "build: generated bundle failed bash -n" >&2; exit 1; }

echo "build: wrote ${OUT}"
